[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[env.production]
  variables = { ENVIRONMENT = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200